# 立ち上げる箱の一覧
services:
  # 箱の名前
  mysql:
    # タグ8.0を付けて固定
    # 既製品を使うからimage, 自分で作るならbuild
    image: "mysql:8.0"
    # 箱の中に渡す設定値
    environment:
      # 起動時に作るDB名
      - "MYSQL_DATABASE=mydatabase"
      # 一般ユーザーのパスワード
      - "MYSQL_PASSWORD=secret"
      # root のパスワード
      - "MYSQL_ROOT_PASSWORD=verysecret"
      # 追加で作る一般ユーザー
      - "MYSQL_USER=myuser"
    # 外とつなぐ番号
    ports:
      # PC側の3306を空けておく
      - "3307:3306"
    volumes:
      # ↓ MySQLの書き込みが起きてほしい場所(mysql-data)を箱の中の/var/lib/mysqlにつなぐ（外：中）
      - "mysql-data:/var/lib/mysql"
    healthcheck:
      # 5秒ごとにmysqladmin pingを売って返事があるか確かめる
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-uroot",
          "-pverysecret",
        ]
      # 確認の間隔
      interval: 5s
      timeout: 5s
      # 20回まで待つ
      retries: 20

  # コンテナ名
  app:
    # このフォルダのDockerfileから自分で作る
    build: .
    # PCの8080をコンテナの8080につなぐ
    ports:
      - "8080:8080"
    # コンテナの中に設定値を渡す
    environment:
      # - "SPRING_DATASOURCE_URL=jdbc:mysql://コンテナの3306/mydatabase"
      - "SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydatabase"
      - "SPRING_DATASOURCE_USERNAME=myuser"
      - "SPRING_DATASOURCE_PASSWORD=secret"
    # mysqlのコンテナを先に起動する
    depends_on:
      mysql:
        # mysqlがhealthyになるまで待つ
        condition: service_healthy

volumes:
  # mysql-data: という置き場を作る
  mysql-data:
